"""Public notebook helpers for the packaged pySTAMPS tutorials."""

from .dataset_inspection import inspect_dataset, inspect_stage1_inputs
from .plots import (
    footprint_compare,
    heatmap_compare,
    hist_compare,
    normalize_points,
    point_count,
    sample_matrix,
    sample_points,
    sample_vector,
    scalar,
    scatter_compare,
    select_points,
)
from .stage_execution import (
    LEGACY_CONTEXT,
    STAGE_PATTERNS,
    build_scratch_tree,
    build_stage_notebook_context,
    build_stage_notebook_context_from_env,
    execute_stage,
    find_repo_root,
    patch_n_ps,
    patch_paths,
    patch_payload,
    root_payload,
    stage3_indices,
    stage4_indices,
)

__all__ = [
    "LEGACY_CONTEXT",
    "STAGE_PATTERNS",
    "build_scratch_tree",
    "build_stage_notebook_context",
    "build_stage_notebook_context_from_env",
    "execute_stage",
    "find_repo_root",
    "footprint_compare",
    "heatmap_compare",
    "hist_compare",
    "inspect_dataset",
    "inspect_stage1_inputs",
    "normalize_points",
    "patch_n_ps",
    "patch_paths",
    "patch_payload",
    "point_count",
    "root_payload",
    "sample_matrix",
    "sample_points",
    "sample_vector",
    "scalar",
    "scatter_compare",
    "select_points",
    "stage3_indices",
    "stage4_indices",
]
